# Generated by Django 4.0.6 on 2022-07-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '__first__'),
        ('user', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.timestampedmodel')),
            ],
            bases=('user.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.timestampedmodel')),
            ],
            bases=('user.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.timestampedmodel')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('content', models.TextField(default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=16)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.author')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
            bases=('user.timestampedmodel',),
        ),
    ]
