
title: Techstructive Blog 
author:
  name: Meet Gor
  email: gormeet711@gmail.com
minima:
  date_format: "%b %-d %Y"
  social_links:
    github: Mr-Destructive 
    twitter: MeetGor21
    linkedin: meetgor
    devto: mr_destructive
description: >- 
 The blog for Constructive Technology. 
baseurl: "techstructive-blog/" 
url: "https://mr-destructive.github.io/" 

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

collections:
  - vim
  - bash
  - python    
  - django
  - svelte
  - web-development  
  - linux
  - hashnode  
  - open-source
  - github
  - competitive-programming
  - object-oriented-programming


