#
#  __  __            _         _         _                  _
# |  \/  | __ _ _ __| | ____ _| |_ __ _ | |_ ___  _ __ ___ | |
# | |\/| |/ _` | '__| |/ / _` | __/ _` || __/ _ \| '_ ` _ \| |
# | |  | | (_| | |  |   < (_| | || (_| || || (_) | | | | | | |
# |_|  |_|\__,_|_|  |_|\_\__,_|\__\__,_(_)__\___/|_| |_| |_|_|
#
#                                           techstructive-blog

[markata]
# bump site version to bust GitHub actions cache
site_version = 2

# 2 weeks in seconds
default_cache_expire = 1209600

## Markata Setup
glob_patterns = "blog/posts/*.md"
## glob_patterns = "pages/**/*spaceflights*.md"
output_dir = "markout"
assets_dir = "static"
hooks = [
    "plugins.feeds",
    "plugins.flat_slug",
    "markata.cli.cli",
    "markata.cli.header",
    "markata.cli.plugins",
    "markata.cli.runner",
    "markata.cli.server",
    "markata.cli.summary",
    "markata.plugins.auto_title",
    "markata.plugins.base_cli",
    "markata.plugins.copy_assets",
    "markata.plugins.covers",
    "markata.plugins.datetime",
    "markata.plugins.docs",
    "markata.plugins.generator",
    "markata.plugins.publish_source",
    "markata.plugins.glob",
    "markata.plugins.icon_resize",
    "markata.plugins.load",
    "markata.plugins.long_description",
    "markata.plugins.post_template",
    "markata.plugins.publish_html",
    "markata.plugins.pyinstrument",
    "markata.plugins.render_markdown",
    "markata.plugins.rss",
    "markata.plugins.sitemap",
    "markata.plugins.to_json",
    "markata.plugins.tui",
    "markata.background",
    "markata.hookspec",
    "markata.lifecycle",
    "markata.errors",
    "markata.standard_config",

#   ]
#   "plugins.render_template_variables",
#   "plugins.codeblocks",
#   "plugins.index",
#   "plugins.slug",
#   "plugins.one_line_link",
#   "plugins.include",
#   "default",
#   # 'plugins.related',
#   'plugins.seo_amp',
#   'plugins.publish_amp',
#   'plugins.custom_seo',
#   'plugins.gif_to_mp4',
#   'plugins.rss_tag',
#   'plugins.auto_publish',
   ]
disabled_hooks = ["markata.plugins.covers", 'markata.plugins.flat_slug', 'markata.plugins.feeds']

## Site Config
url = "https://mr-destructive.github.io/techstructive-blog"
title = "Techstructive Blog"
description = "Writing about Vim | Python | Django and Linux"
rss_description = "Techstructive Blog Feed"
author_name = "Meet Gor"
author_email = "gormeet711@gmail.com"
icon = "tbicon.png"
lang = "en"
post_template = "layouts/post_template.html"
amp_template = "layouts/post_template.amp.html"
theme_color = "#00003f"
background_color = "#00003f"
start_url = "/techstructive-blog/"
site_name = "Techstructive Blog"
short_name = "tb"
display = "minimal-ui"
twitter_card = "summary_large_image"
twitter_creator = "@MeetGor21"
twitter_site = "@MeetGor21"

[markata.auto_publish.filters]
til='templateKey=="til" and date>=today'

[markata.archive]
archive_template="layouts/post_template.html"

[markata.archive.pages.archive]
filter="date<=today and templateKey=='blog-post' and status.lower()=='published'"

[markata.archive.pages.draft]
filter="status=='draft'"

[markata.archive.pages.scheduled]
filter="date>today"

[markata.archive.pages.today]
filter="date==today"

[markata.archive.pages.python]
filter="date<=today and 'python' in tags"

[markata.archive.pages.python-draft]
filter="date<=today and 'python' in tags and status=='draft'"

[markata.archive.pages.linux]
filter="date<=today and 'linux' in tags"

[markata.archive.pages.linux-draft]
filter="date<=today and 'linux' in tags and status=='draft'"

[markata.archive.pages.vim]
filter="date<=today and 'vim' in tags"

[markata.archive.pages.vim-draft]
filter="date<=today and 'vim' in tags and status=='draft'"

[markata.archive.pages.til]
template="layouts/archive_template.html"
# card_template="pages/templates/gratitude_card.html"
filter="date<=today and templateKey == 'til'"

[markata.archive.pages.til-vim]
template="layouts/archive_template.html"
# card_template="pages/templates/gratitude_card.html"
filter="date<=today and templateKey == 'til' and 'vim' in tags"

[[markata.covers]]
name='-dev'
template = "static/cover-template.png"
font = "./.github/scripts/waterlilly-script.ttf"
font_color = "rgb(255,255,255)"

[[markata.covers]]
name='-og'
template = "static/og-template.png"
font = "./.github/scripts/waterlilly-script.ttf"
font_color = "rgb(255,255,255)"
# text_key = 'long_description'
text_font = "./static/JosefinSans-Regular.ttf"
text_font_color = "rgb(200,200,200)"

[[markata.covers]]
name='-hashnode'
template = "static/hashnode-template.png"
font = "./.github/scripts/waterlilly-script.ttf"
font_color = "rgb(255,255,255)"

