# Generated by Django 4.0.6 on 2022-07-31 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
